@extends('layouts.app')

@section('content')
<div class="container-fluid bg-primary">
    <div class="container py-4">
        <h1 class="text-left pt-5 text-white">Conditions Générales de vente</h1>
    </div>
</div>
    <div class="container">
        <div class="mt-5">
            <p class="p1"><span class="s1">Les présentes conditions générales de vente s’appliquent à tout utilisateur du site <a href="https://www.iziplans.com"><span class="s2">www.iziplans.com</span></a> dès lors qu’il crée un compte utilisateur. En s’inscrivant, l’utilisateur reconnait avoir lu les conditions générales de vente et conditions d’utilisation du site et je les accepte, il se formera un accord entre la société Nyleo Conception et l’utilisateur qui s’engage dès lors à respecter l’ensemble des conditions précitées, et pour ce qui est des conditions de vente, ce qui suit :</span></p>
            <p class="p1"><span class="s1">1.Présentation du site <a href="https://www.iziplans.com"><span class="s2">www.iziplans.com</span></a></span></p>
            <p class="p1"><span class="s1">Iziplans.com (ci-après Le Site) est une plateforme publiée sur internet qui met en relations différents Utilisateurs qu’ils soient des particuliers ou des professionnels. Le Site est la propriété de la société Nyleo Conception qui en est l’éditrice tel qu’indiqué dans les mentions légales.</span></p>
            <p class="p1"><span class="s1">L’Utilisateur peut être soit un prestataire (indépendant, freelance ou société) à la recherche d’un client, soit un client (aussi appelé porteur de projet) à la recherche d’un prestataire.</span></p>
            <p class="p1"><span class="s1">Le Site permet à un Utilisateur client de publier son annonce de recherche d’un prestataire et il fournit d’autres services payants (ci-après Services). En agissant uniquement comme plateforme de mise en relation, la société Nyleo Conception ne peut être tenue pour responsable des relations commerciales qui se créent ensuite entre les Utilisateurs.</span></p>
            <p class="p1"><span class="s1">2. Définition du terme Utilisateur</span></p>
            <p class="p1"><span class="s1">Le terme « Utilisateur » s’applique à toute personne physique ou morale qui a créé un compte client sur le Site et s’y est enregistré en ayant lu et accepté les présentes conditions et celles d’utilisation du Site.</span></p>
            <p class="p1"><span class="s1">Si l’Utilisateur est à la recherche d’un prestataire, il peut donc aussi prendre la dénomination de Client ou Porteur de projet au sein des présentes conditions générales de vente.</span></p>
            <p class="p1"><span class="s1">Si l’Utilisateur est à la recherche d’un client ou d’un Porteur de projet, il est donc un prestataire qui peut aussi prendre la dénomination de Freelance, Indépendant ou Entreprise au sein des présentes conditions générales de vente.</span></p>
            <p class="p1"><span class="s1">3. Inscription sur le Site</span></p>
            <p class="p1"><span class="s1">L’inscription sur le Site est gratuite pour les Porteurs de projet qui peuvent toutefois choisir de souscrire certaines options ou services payants. </span></p>
            <p class="p1"><span class="s1">L’inscription est gratuite pour les Utilisateurs prestataires mais pour répondre aux annonces des Porteurs de projet, ils doivent souscrire un abonnement payant décrit à l’article 4 ci-dessous.</span></p>
            <p class="p1"><span class="s1">Lors de son inscription sur le Site, l’Utilisateur complètera un formulaire en fournissant ses coordonnées ainsi que toutes les informations sollicitées. Il s’engage à ce que l’ensemble des informations ainsi fournies soient véridiques et la société Nyleo Conception ne pourra pas être tenue responsable de toute erreur dans ces informations fournies uniquement par l’Utilisateur.</span></p>
            <p class="p1"><span class="s1">Pour toutes questions relatives aux termes et conditions d’utilisation ainsi que sur le fonctionnement du Site vous pouvez envoyer un mail à l’adresse contact@iziplans.com</span></p>
            <p class="p1"><span class="s1">4.Les services </span></p>
            <p class="p1"><span class="s1"> 4.1 Sur les services en général</span></p>
            <p class="p1"><span class="s1">Le Site propose des services aux Utilisateurs qu’ils soient Porteurs de Projet ou Prestataires.</span></p>
            <p class="p1"><span class="s1">En tant qu’intermédiaire entre les Utilisateurs, le Site ne contrôle pas les échanges qui s’effectuent directement entre ces derniers. Le Site n’intervient donc à aucun moment dans la détermination du prix d’une prestation de service, et dans les modalités de son exécution qui sont seules définies entre les Utilisateurs Prestataires et les Porteurs de projet.</span></p>
            <p class="p1"><span class="s1">De même, le Site n’effectue aucun contrôle de la capacité juridique de l’Utilisateur, de la réalité de son offre pas plus que de la qualité d’un Prestataire ni de son aptitude à facture un Porteur de Projet.</span></p>
            <p class="p1"><span class="s1">Il appartient aux Utilisateurs mis en relation de vérifier chacun la réalité et le sérieux de ce que propose son interlocuteur.</span></p>
            <p class="p1"><span class="s1">Il est en outre strictement interdit aux Utilisateurs de mentionner des informations de contact, informations bancaires, coordonnées professionnelles et/ou personnelles dans le texte d’une annonce d’un projet ainsi que dans le texte de présentation du profil de l’Utilisateur Prestataire et au sein de la messagerie du Site.</span></p>
            <p class="p1"><span class="s1">En cas de violation de l’une de ces restrictions formelles, le Site aura le droit de fermer un compte d’Utilisateur à tout instant et sans préavis. Le Site se réserve aussi le droit de ne pas publier l’annonce.</span></p>
            <p class="p1"><span class="s1">En conséquence, les coordonnées et l’identité de l’Utilisateur doivent être occultées jusqu’au choix définitif du Prestataire par le Porteur de projet.</span></p>
            <p class="p1"><span class="s1">Pour faciliter la mise en relation entre les Utilisateurs Porteurs de projet et les Prestataires, le Site a mis en place une messagerie privée accessible depuis l’espace « Mon compte » de l’Utilisateur. Tous les échanges entre les Utilisateurs doivent être réalisés au travers de cette messagerie.</span></p>
            <p class="p1"><span class="s1">Le Site offre aussi un service d’évaluation qui permet au Porteur de projet de noter le travail du Prestataire selon certains critères, une fois le projet terminé.</span></p>
            <p class="p1"><span class="s1">Un projet connaît plusieurs statuts :</span></p>
            <ul class="ul1">
            <li class="li1"><span class="s1">« Actif » Lorsque le projet est créé et que les Prestataires peuvent envoyer leurs devis</span></li>
            <li class="li1"><span class="s1">« Attribué » Lorsque le Porteur de projet a choisi son Prestataire. Cela évite aux autres candidats d’envoyer des devis.</span></li>
            <li class="li1"><span class="s1">« Fermé » lorsque le Porteur de projet renonce à son annonce ou ne souhaite plus recevoir de devis</span></li>
            <li class="li1"><span class="s1">« Terminé » lorsque le prestataire déclare avoir fini son travail.</span></li>
            </ul>
            <p class="p1"><span class="s1">Le changement de statut s’effectue depuis l’interface « Mon profil » par la personne concernée.</span></p>
            <p class="p1"><span class="s1">Le Site ne facture aucune commission auprès des Prestataires pour le travail accompli et le marché qu’ils ont conclu avec un Porteur de projet.</span></p>
            <p class="p1"><span class="s1">En tant que simple intermédiaire, le Site n’est pas responsable en cas de litige entre Utilisateurs portant sur la qualité d’un travail, le non-paiement du prix convenu, le retard apporté à un travail etc… Les Utilisateurs sont donc invités à régler leurs litiges entre eux par toutes voies de droit qu’ils jugent nécessaires.</span></p>
            <p class="p3"><span class="s1">4.2 Les services payants</span></p>
            <p class="p4"><span class="s1">Le Site propose aux Utilisateurs Prestataires un système d’abonnement mensuel renouvelable tacitement et automatiquement. Pour les Utilisateurs Porteurs de projet, le Site propose des options payantes.</span></p>
            <p class="p4"><span class="s1">Tous ces services payants peuvent être modifiés et/ou supprimés à tout moment et sans préavis par le Site.</span></p>
            <p class="p5"><span class="s1">4.2.1 Abonnements pour les Prestataires </span></p>
            <p class="p4"><span class="s1">Les abonnements ont une durée de 30 jours et sont payables d’avance sans remboursement possible.</span></p>
            <p class="p4"><span class="s1">Ils se renouvellent automatiquement à chaque fin de période de 30 jours. L’Utilisateur peut supprimer le renouvellement automatique en cliquant sur la case « Résilier » dans l’onglet « Mon profil ».</span></p>
            <p class="p4"><span class="s1">La désactivation / résiliation de l’abonnement est à effet immédiat et sans remboursement si elle intervient en cours de période de validité. Tout mois commencé est donc dû.</span></p>
            <p class="p1"><span class="s1">Si l’Utilisateur souhaite changer de type d’abonnement, il doit d’abord désactiver celui en cours pour ensuite cliquer sur « Renouveler » et souscrire un nouvel abonnement. </span></p>
            <p class="p1"><span class="s1">5.<span class="Apple-converted-space">  </span>Projets</span></p>
            <p class="p1"><span class="s1">La publication d’un projet est gratuite sauf si le Porteur de Projet choisit de souscrire une option payante au moment de sa création.</span></p>
            <p class="p1"><span class="s1">Après avoir reçu des réponses et échangé avec un ou plusieurs Prestataires au travers de la messagerie privée du Site, le Porteur de Projet choisit un Prestataire pour qu’il réalise son projet.</span></p>
            <p class="p1"><span class="s1">Il incombe au Porteur de Projet de vérifier la réalité des informations reçues de la part du Prestataire ainsi que sa capacité à pouvoir facturer sa prestation en toute légalité.</span></p>
            <p class="p1"><span class="s1">Le Site ne pourra pas être tenu pour responsable d’un manquement du Prestataire sur ses compétences et sa capacité à facturer.</span></p>
            <p class="p1"><span class="s1">Le Site se réserve le droit de modifier à tout moment un projet en cas de faute d’orthographe, d’information incomplète, de publication d’un contenu non autorisé ou ayant la nature d’une publicité. </span></p>
            <p class="p1"><span class="s1">Si le Porteur de Projet ne trouve aucun Prestataire correspondant à son offre, il lui suffira alors simplement de fermer son projet pour éviter de continuer à recevoir des réponses. Le Site pourra quant à lui décider de fermer un projet si l’annonce est restée inactive pendant plus de 15 jours et en tout état de cause, un projet se ferme automatiquement passé le 60</span><span class="s3"><sup>ème</sup></span><span class="s1"> jour de sa publication.</span></p>
            <p class="p1"><span class="s1">Une fois le Prestataire choisi par le Porteur de Projet, le Site n’intervient plus ni dans la conclusion du contrat, ni dans la facturation, ni dans la gestion d’éventuels litiges entre les deux utilisateurs. Le Site ne propose qu’un outil de mise en relation.</span></p>
            <p class="p1"><span class="s1">Il est en outre formellement interdit lors de la publication d’un projet de mentionner dans l’annonce des informations de contact, des coordonnées professionnelles, personnelles ou bancaires et il en va de même lors des échanges entre utilisateurs par le biais de la messagerie privée du site.</span></p>
            <p class="p1"><span class="s1">En cas de violation de cette interdiction, le site sera en droit de résilier et clôturer le compte de l’Utilisateur contrevenant à tout moment et sans préavis et pourra ne pas publier le projet.</span></p>
            <p class="p1"><span class="s1">L’identité du Prestataire sera communiquée au Porteur de Projet lorsqu’il aura validé son choix concernant le freelance qui réalisera son projet.</span></p>
            <p class="p1"><span class="s1">6. Profils Utilisateurs</span></p>
            <p class="p1"><span class="s1">Lors de son inscription, chaque catégorie d’Utilisateur complète un formulaire sous sa seule responsabilité et s’engage sur la réalité des informations communiquées. Si l’Utilisateur constate une erreur dans son profil, il peut la corriger ultérieurement en accédant à l’espace « Mon profil »</span></p>
            <p class="p1"><span class="s1">En s’inscrivant sur le Site, le Prestataire reconnaît et déclare avoir la capacité légale de facturer en France un client et si par extraordinaire tel ne devait pas être le cas, alors le Site n’en sera pas tenu responsable.</span></p>
            <p class="p1"><span class="s1">Après son inscription, chaque Utilisateur peut accéder à l’espace « Mon compte » grâce à ses identifiants. Celui-ci est différent selon qu’il concerne un Porteur de Projet ou un Prestataire.</span></p>
            <p class="p1"><span class="s1">Cet espace comporte en outre des onglets permettant notamment de consulter ses informations d’inscription, projets, éventuelles factures, et la messagerie privée.</span></p>
            <p class="p1"><span class="s1">Le Site se réserve le droit de modifier à tout moment le contenu et la configuration des espaces «Mon compte » </span></p>
            <p class="p1"><span class="s1">7. Atteinte à l’intégrité du système</span></p>
            <p class="p1"><span class="s1">Aucun Utilisateur n’est autorisé à utiliser des dispositifs, logiciels ou algorithme, susceptibles de porter atteinte au bon fonctionnement du Site et à l’intégrité de son système. Toute tentative d’actions de nature à causer des dommages ou à s’opposer au bon fonctionnement du Site sera susceptible d’entraîner des poursuites judiciaires. De même, il est interdit de mener des actions visant à surcharger le système, tels que des « Spam » ou autre technique d’envois d’email massifs. </span></p>
            <p class="p1"><span class="s1">Par ailleurs, afin d’éviter tout risque de triche concernant les évaluations laissées par les Utilisateurs, ces derniers ne doivent pas s’être connus en dehors du Site avant que le projet ne soit réalisé.</span></p>
            <p class="p1"><span class="s1">8. Informations publiées sur le Site </span></p>
            <p class="p1"><span class="s1">Les Utilisateurs sont seuls responsables des informations qu’ils publient sur le Site et ce y compris les messages laissés et envoyés via la messagerie privée.</span></p>
            <p class="p1"><span class="s1">Il est rappelé que ces informations ne doivent pas porter atteinte aux droits des tiers tels que droits de la propriété intellectuelle, publicité, ou à la vie privée. Elles ne doivent pas être diffamatoires, menaçantes, obscènes, discriminatoires ou racistes. Même si le Site n’est pas responsable des publications des Utilisateurs, il se réserve le droit de les supprimer sans préavis ou de clôturer un compte en cas de non-respect du présent alinéa.</span></p>
            <p class="p1"><span class="s1">Le Site peut en outre contenir des liens vers des site web extérieurs qui ne sont pas contrôlés par le Site, lequel n’est donc pas responsable de leur contenu.</span></p>
            <p class="p1"><span class="s1">Les informations concernant les Prestataires telles que leurs compétences, expériences, évaluations, ne sont pas contrôlées par le Site et sont donc publiées sous l’entière responsabilité des Prestataires. </span></p>
            <p class="p1"><span class="s1">Il en va de même des projets publiés par les Porteurs de Projet qui ne sont pas toujours vérifiés et sont donc publiés sous leur seule responsabilité.</span></p>
            <p class="p1"><span class="s1">9.Litiges entre Utilisateurs</span></p>
            <p class="p1"><span class="s1">Le Site n’agit que comme un intermédiaire entre les Utilisateurs de telle sorte qu’il ne pourra jamais intervenir de quelque manière que ce soit dans un litige survenu entre eux à l’occasion de leurs relations.</span></p>
            <p class="p1"><span class="s1">La relation qui existe entre le Site et les Utilisateurs est uniquement de nature commerciale dans la mesure où le site vend une prestation. Cette relation ne pourra en aucun cas être qualifiée de relation de travail puisqu’il n’existe aucun lien de subordination entre les Utilisateurs et le Site. Les Utilisateurs agissent de leur plein gré et ne recevront jamais aucune instruction de la part du Site concernant leurs propres prestations ou projets.</span></p>
            <p class="p1"><span class="s1">Le Site ne rémunère pas les Prestataires qui se font payer uniquement par les Porteurs de Projets qui les auront préalablement sélectionnés. Ils sont libres de fixer le montant de leur prestation et leurs conditions de paiement.</span></p>
            <p class="p1"><span class="s1">Les Utilisateurs contractent entre eux et sont seuls en mesure de régler leurs litiges par tout moyen qu’ils jugent nécessaires et en dehors de la responsabilité et de l’intervention ou mise en cause du Site.</span></p>
            <p class="p1"><span class="s1">10.Paiements</span></p>
            <p class="p1"><span class="s1">Tous les paiements effectués sur le Site pour régler les abonnements ou les services optionnels sont sécurisés.</span></p>
            <p class="p1"><span class="s1">Le site utilise la solution de paiement Stripe</span> <span class="s1">afin de garantir un paiement sécurisé et de qualité.</span></p>
            <p class="p1"><span class="s1">Les moyens de paiements proposés sont : carte bancaire (Visa, Mastercard, American Express), Paypal. Le Site se réserve le droit de modifier ou supprimer à tout moment un moyen de paiement.</span></p>
            <p class="p1"><span class="s1">Pour les paiements récurrents tels que ceux des abonnements, la carte bancaire qui a servi à effectuer le premier règlement lors de la souscription sera ensuite débitée tous les 30 jours à compter de la date de souscription et ce uniquement si le renouvellement automatique est activé. </span></p>
            <p class="p1"><span class="s1">En cas de défaut de paiement (carte refusée, expirée ou autre) un mail sera envoyé à l’Utilisateur pour l’avertir de l’échec de la transaction et l’invitant à contacter sans délai le Site afin de régulariser la situation. Les services ainsi impayés seront suspendus immédiatement jusqu’à régularisation de la situation. </span></p>
            <p class="p1"><span class="s1">En aucun cas le Site ne peut envoyer une facture relative à la réalisation d’un projet par un Prestataire. Celui-ci envoie directement sa facture au Porteur de Projet qui l’a sélectionné.</span></p>
            <p class="p1"><span class="s1">11. Propriété et droit</span></p>
            <p class="p1"><span class="s1">Le Site ainsi que tous les droits de propriété intellectuelle qui en découlent, incluant notamment copyright, marques déposées, avis laissés par les Utilisateurs, publications, graphismes, photos, images, textes, appartiennent au Site. Les Utilisateurs ne sont pas autorisés à reproduire et utiliser l’un quelconque des éléments présents dans le Site. Une partie du contenu du Site peut aussi faire l’objet d’une licence d’exploitation et appartenir en conséquence à un tiers.</span></p>
            <p class="p1"><span class="s1">Le Site se réserve le droit d’effacer, de suspendre ou de clôturer immédiatement le compte des Utilisateurs qui ne respecteraient pas l’une des conditions générales de vente ou conditions générales d’utilisation qu’ils ont acceptées lors de leur inscription.</span></p>
            <p class="p1"><span class="s1">Le Site est autorisé à publier, à titre de référence client, les noms de sociétés, logos de sociétés, et/ou nom d’utilisateurs faisant appel à ses services. </span></p>
            <p class="p1"><span class="s1">Les Utilisateurs en acceptant les présentes conditions générales reconnaissent qu’ils ont donné au Site l’autorisation d’utiliser leur nom et/ou logo afin d’indiquer à des tiers qu’ils ont fait appel aux services du Site. Cette utilisation pourra être effectuée soit directement sur l’une des pages du site soit sur tout autre support que le Site jugerait utile à sa promotion.</span></p>
            <p class="p1"><span class="s1">Toutefois, si vous souhaitez que le Site n’utilise pas le nom de votre société publiquement ou votre logo, vous pouvez en faire la demande par email ou au travers du formulaire de contact.</span></p>
            <p class="p1"><span class="s1">12.Limitation de responsabilité</span></p>
            <p class="p1"><span class="s1">La société propriétaire du Site n’est en aucun cas responsable des dommages, de quelque nature que ce soit résultant de l’accès à ce Site ou de son utilisation, ou encore de toute information contenue sur le Site. </span></p>
            <p class="p1"><span class="s1">Elle ne saurait ainsi être tenue responsable de l’interruption de service liée notamment à la maintenance du Site ou à un défaut ou rupture dans la prestation d’hébergement du Site.</span></p>
            <p class="p1"><span class="s1">Elle ne saurait davantage être tenue responsable des pertes de données ou de l’échec d’une transaction résultant du retard, de la non-livraison ou de l’erreur de livraison de l’un des services fournis par le Site.</span></p>
            <p class="p1"><span class="s1">Les Utilisateurs renoncent également à exercer tout recours contre la société propriétaire du Site dans le cas de poursuites judiciaires menées par un tiers à son encontre du fait de l’utilisation et/ou de l’exploitation du Site ou, en cas de perte par un Utilisateur de son mot de passe ou en cas d’usurpation de son identité.</span></p>
            <p class="p1"><span class="s1">13.Dispositions générales </span></p>
            <p class="p1"><span class="s1">Le contrat est conclu intuitu personae entre le Site et l’Utilisateur de telle sorte que les droits et obligations qui en résultent ne peuvent être cédés, partiellement ou totalement, à des tiers, sauf en cas de fusion absorption de l’un ou de l’autre par un tiers. Le fait que le Site n’exerce pas ou n’applique pas un droit ou une disposition des présentes conditions générales ne doit pas s’analyser en un renoncement à ce droit ou à cette disposition.</span></p>
            <p class="p1"><span class="s1">Tout litige relatif à l’exécution ou à l’interprétation des présentes conditions générales de vente et des conditions générales d’utilisation du Site seront de la compétence territoriale du Tribunal de Commerce de Périgueux Le droit français sera applicable et la langue de procédure sera la langue Française quelle que soit la nationalité de l’une quelconque des parties au litige ou à la procédure. </span></p>
            <p class="p1"><span class="s1">14. Newsletters et notifications</span></p>
            <p class="p1"><span class="s1">En s’inscrivant sur le Site l’Utilisateur accepte expressément et donne son accord pour recevoir la newsletter et les notifications d’emails du Site.</span></p>
            <p class="p1"><span class="s1">L’Utilisateur peut se désinscrire à tout moment de la newsletter via le lien spécifique inclus dans le mail à cet effet. Si aucun lien n’est affiché dans le mail ou s’il ne fonctionne pas, l’Utilisateur peut demander sa désinscription via le formulaire de contact.</span></p>
            <p class="p1"><span class="s1">L’attention de l’Utilisateur est cependant attirée sur le fait que les notifications reçues (comme par exemple l’alerte sur un nouveau projet, l’alerte sur un nouveau message reçu, etc…) ne sont pas des newsletters ou des emails commerciaux.<span class="Apple-converted-space">  </span>Ces notifications sont envoyées et il n’est pas possible de se désinscrire tant que l’Utilisateur a son compte actif sur le Site. Pour ne plus les recevoir il suffit de demander la résiliation du compte Utilisateur via le formulaire de contact.</span></p>
        </div>
    </div>

@endsection
