language: php
​
sudo: false
​
php:
  - 7.3
​
install:
  - composer install

deploy:
  provider: elasticbeanstalk
  access_key_id: ${AWS_ACCESS_KEY_ID}
  secret_access_key: ${AWS_SECRET_ACCESS_KEY}
  region: eu-west-3
  app: iziplans
  env: preprod
  bucket: elasticbeanstalk-eu-west-3-631563697254
  wait_until_deployed: true
  edge: true # opt in to dpl v2