version: "3.7"

services:
  app:
    image: mickael/iziplans
    container_name: iziplans-app
    restart: unless-stopped
    working_dir: /var/www/
    build:
      args:
        user: mickael
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www
    networks:
      default:
        aliases:
          - iziplans.app

  nginx:
    image: nginx:1.17-alpine
    container_name: iziplans-nginx
    restart: unless-stopped
    ports:
      - 8080:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/

  mysql:
    image: mysql:5.7
    container_name: iziplans-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - mysql-volume:/var/lib/mysql
    networks:
      default:
        aliases:
          - iziplans.mysql

volumes:
  mysql-volume:
    name: iziplans-mysql-volume